name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run dist

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: npm run dist:win

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: npm run dist:mac

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.os }}
          path: release/