name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: macos

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Linux dependencies
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm-dev libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libxss-dev libasound2-dev

      - name: Build application
        run: npm run build

      - name: Check build output (Unix)
        if: matrix.platform != 'windows'
        run: |
          echo "Checking dist directory structure:"
          find dist -type f -name "*.js" | head -10 || echo "No JS files found in dist"
          echo "Checking main.js exists:"
          if [ -f "dist/main/main.js" ]; then echo "main.js found at dist/main/main.js"; else echo "main.js NOT found"; fi
          echo "File size of main.js:"
          ls -la dist/main/main.js || echo "Cannot check file size"

      - name: Build for Linux
        if: matrix.platform == 'linux'
        run: npm run dist:linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder

      - name: Check build output (Windows)
        if: matrix.platform == 'windows'
        run: |
          Write-Host "Checking dist directory structure:"
          Get-ChildItem -Path "dist" -Recurse -Name "*.js" | Select-Object -First 10
          Write-Host "Checking main.js exists:"
          if (Test-Path "dist\main\main.js") {
            Write-Host "main.js found at dist\main\main.js"
            Write-Host "File size:"
            Get-Item "dist\main\main.js" | Select-Object Length
          } else {
            Write-Host "main.js NOT found"
          }

      - name: Build for Windows
        if: matrix.platform == 'windows'
        run: npm run dist:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder

      - name: Build for macOS
        if: matrix.platform == 'macos'
        run: npm run dist:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: release-${{ matrix.platform }}
          path: release/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && always()

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
        continue-on-error: true

      - name: List available artifacts
        run: find ./artifacts -type f -name "*" || echo "No artifacts found"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}